"""
schemas.py — Pydantic v2 models for request/response validation.

Shared across routes and agents to enforce consistent data shapes.
"""

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# API request models
# ---------------------------------------------------------------------------

class PipelineRequest(BaseModel):
    """POST /pipeline request body."""

    doc_type: str = Field(
        ...,
        description=(
            "One of: fir, legal_notice, consumer_complaint, "
            "cheque_bounce, tenant_eviction"
        ),
    )
    description: str = Field(
        ...,
        min_length=10,
        description="User's description of their legal situation (Hindi/English/Hinglish)",
    )
    session_id: str = Field(
        ...,
        description="UUID generated by the frontend to identify this pipeline run",
    )


# ---------------------------------------------------------------------------
# Agent data models
# ---------------------------------------------------------------------------

class LegalSection(BaseModel):
    """A single applicable law section identified by LegalResearchAgent."""

    act: str = Field(..., description="Full name of the Act, e.g. 'BNS 2023'")
    section: str = Field(..., description="Section number, e.g. 'Section 103'")
    description: str = Field(..., description="One-line summary of the section")


class IncidentJSON(BaseModel):
    """Structured case data extracted by IntakeAgent."""

    incident_type: str
    parties: dict[str, Any] = Field(default_factory=dict)
    date_of_incident: Optional[str] = None
    location: Optional[str] = None
    description: str
    relief_sought: Optional[str] = None
    doc_type: str


class VerificationResult(BaseModel):
    """Output from VerifierAgent — quality report on the drafted document."""

    is_complete: bool = False
    overall_quality: str = Field(
        default="acceptable",
        description="good | acceptable | poor",
    )
    flags: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
    missing_fields: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# SSE event model
# ---------------------------------------------------------------------------

class PipelineEvent(BaseModel):
    """Shape of every SSE event pushed to the frontend."""

    agent: str = Field(
        ...,
        description="intake | research | drafter | verifier | system",
    )
    status: str = Field(
        ...,
        description="running | complete | error",
    )
    data: dict[str, Any] = Field(default_factory=dict)
